import transporter from "../config/emailConfig.js";
import Monitor from "../models/monitor.model.js";
import User from "../models/user.model.js";
import config from "../config/config.js";

// ─── SEND EMAIL ────────────────────────────────────────────

const sendEmailAlert = async ({ to, subject, html }) => {
  try {
    await transporter.sendMail({
      from: `"PulseWatch" <onboarding@resend.dev>`,
      to,
      subject,
      html,
    });
    console.log(`📧 Alert email sent to ${to}`);
  } catch (err) {
    console.error("Email alert failed:", err.message);
  }
};

// ─── HTML TEMPLATES ────────────────────────────────────────

const buildIncidentEmail = ({ monitorName, url, type, startTime }) => {
  const isDown = type === "DOWN";

  return `
  <div style="margin:0;padding:0;background-color:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif">
    <div style="max-width:600px;margin:40px auto;background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden">

      <!-- Header -->
      <div style="padding:20px 24px;background:${isDown ? "#FEF2F2" : "#FFFBEB"};border-bottom:1px solid #e5e7eb">
        <h2 style="margin:0;font-size:18px;color:${isDown ? "#B91C1C" : "#B45309"}">
          ${isDown ? "🚨 Service Down" : "⚠️ Service Degraded"}
        </h2>
        <p style="margin:4px 0 0;color:#6b7280;font-size:13px">
          We detected an issue with your monitored service.
        </p>
      </div>

      <!-- Body -->
      <div style="padding:24px">
        <table style="width:100%;border-collapse:collapse;font-size:14px">
          <tr>
            <td style="padding:10px 0;color:#6b7280">Monitor</td>
            <td style="padding:10px 0;font-weight:600;color:#111827">${monitorName}</td>
          </tr>
          <tr>
            <td style="padding:10px 0;color:#6b7280">URL</td>
            <td style="padding:10px 0">
              <a href="${url}" style="color:#2563eb;text-decoration:none">${url}</a>
            </td>
          </tr>
          <tr>
            <td style="padding:10px 0;color:#6b7280">Status</td>
            <td style="padding:10px 0;font-weight:700;color:${isDown ? "#DC2626" : "#D97706"}">
              ${type}
            </td>
          </tr>
          <tr>
            <td style="padding:10px 0;color:#6b7280">Started</td>
            <td style="padding:10px 0;color:#111827">
              ${new Date(startTime).toLocaleString()}
            </td>
          </tr>
        </table>
      </div>

      <!-- Footer -->
      <div style="padding:16px 24px;border-top:1px solid #e5e7eb;background:#fafafa">
        <p style="margin:0;font-size:12px;color:#9ca3af">
          This alert was generated by <strong>PulseWatch Monitoring</strong>.
        </p>
      </div>

    </div>
  </div>
  `;
};

const buildResolvedEmail = ({ monitorName, url, type, endTime, duration }) => {
  return `
  <div style="margin:0;padding:0;background-color:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif">
    <div style="max-width:600px;margin:40px auto;background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden">

      <!-- Header -->
      <div style="padding:20px 24px;background:#ECFDF5;border-bottom:1px solid #e5e7eb">
        <h2 style="margin:0;font-size:18px;color:#065F46">
          ✅ Incident Resolved
        </h2>
        <p style="margin:4px 0 0;color:#6b7280;font-size:13px">
          Your service is back to normal operation.
        </p>
      </div>

      <!-- Body -->
      <div style="padding:24px">
        <table style="width:100%;border-collapse:collapse;font-size:14px">
          <tr>
            <td style="padding:10px 0;color:#6b7280">Monitor</td>
            <td style="padding:10px 0;font-weight:600;color:#111827">${monitorName}</td>
          </tr>
          <tr>
            <td style="padding:10px 0;color:#6b7280">URL</td>
            <td style="padding:10px 0">
              <a href="${url}" style="color:#2563eb;text-decoration:none">${url}</a>
            </td>
          </tr>
          <tr>
            <td style="padding:10px 0;color:#6b7280">Previous Status</td>
            <td style="padding:10px 0;color:#111827">${type}</td>
          </tr>
          <tr>
            <td style="padding:10px 0;color:#6b7280">Resolved At</td>
            <td style="padding:10px 0;color:#111827">
              ${new Date(endTime).toLocaleString()}
            </td>
          </tr>
          <tr>
            <td style="padding:10px 0;color:#6b7280">Duration</td>
            <td style="padding:10px 0;font-weight:600;color:#111827">
              ${duration}
            </td>
          </tr>
        </table>
      </div>

      <!-- Footer -->
      <div style="padding:16px 24px;border-top:1px solid #e5e7eb;background:#fafafa">
        <p style="margin:0;font-size:12px;color:#9ca3af">
          This notification was sent by <strong>PulseWatch Monitoring</strong>.
        </p>
      </div>

    </div>
  </div>
  `;
};

// ─── HELPERS ───────────────────────────────────────────────

const formatDuration = (ms) => {
  const s = Math.floor(ms / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ${s % 60}s`;
  const h = Math.floor(m / 60);
  return `${h}h ${m % 60}m`;
};

const getMonitorOwner = async (monitorId) => {
  const monitor = await Monitor.findById(monitorId).lean();
  if (!monitor) return null;
  const user = await User.findById(monitor.userId)
    .select("email username")
    .lean();
  return { monitor, user };
};

// ─── PUBLIC API ────────────────────────────────────────────

/**
 * Called when a new incident is created
 */
export const notifyIncidentCreated = async ({ monitorId, type, startTime }) => {
  try {
    const data = await getMonitorOwner(monitorId);
    if (!data?.user?.email) return;

    const { monitor, user } = data;
    console.log("🔍 Alert debug:", {
      monitorId,
      alertEmail: monitor.alertEmail,
      userEmail: user.email,
      sendingTo: monitor.alertEmail || user.email,
    });
    const monitorName = monitor.name || monitor.url;

    await sendEmailAlert({
      to: monitor.alertEmail || user.email,
      subject: `🚨 ${type}: ${monitorName} is ${type}`,
      html: buildIncidentEmail({
        monitorName,
        url: monitor.url,
        type,
        startTime,
      }), // Remove problem from here
    });
  } catch (err) {
    console.error("Alert (created) error:", err.message);
  }
};

/**
 * Called when an incident is resolved
 */
export const notifyIncidentResolved = async ({
  monitorId,
  type,
  startTime,
  endTime,
}) => {
  try {
    const data = await getMonitorOwner(monitorId);
    if (!data?.user?.email) return;

    const { monitor, user } = data;
    const monitorName = monitor.name || monitor.url;
    const duration = formatDuration(new Date(endTime) - new Date(startTime));

    await sendEmailAlert({
      to: monitor.alertEmail || user.email,
      subject: `✅ Resolved: ${monitorName} is back UP`,
      html: buildResolvedEmail({
        monitorName,
        url: monitor.url,
        type,
        endTime,
        duration,
      }),
    });
  } catch (err) {
    console.error("Alert (resolved) error:", err.message);
  }
};

/**
 * Called when an incident has been down for 3+ minutes (escalation alert)
 */
export const notifyIncident3MinDown = async ({
  monitorId,
  type,
  startTime,
}) => {
  try {
    const data = await getMonitorOwner(monitorId);
    if (!data?.user?.email) return;

    const { monitor, user } = data;
    const monitorName = monitor.name || monitor.url;
    const downDuration = formatDuration(new Date() - new Date(startTime));

    const html = `
    <div style="margin:0;padding:0;background-color:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif">
      <div style="max-width:600px;margin:40px auto;background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden">

        <!-- Header -->
        <div style="padding:20px 24px;background:#7C2D12;border-bottom:1px solid #e5e7eb">
          <h2 style="margin:0;font-size:18px;color:#FFFFFF">
            🔴 CRITICAL: Prolonged Outage
          </h2>
          <p style="margin:4px 0 0;color:#FECACA;font-size:13px">
            Your service has been down for more than 3 minutes.
          </p>
        </div>

        <!-- Body -->
        <div style="padding:24px">
          <table style="width:100%;border-collapse:collapse;font-size:14px">
            <tr>
              <td style="padding:10px 0;color:#6b7280">Monitor</td>
              <td style="padding:10px 0;font-weight:600;color:#111827">${monitorName}</td>
            </tr>
            <tr>
              <td style="padding:10px 0;color:#6b7280">URL</td>
              <td style="padding:10px 0">
                <a href="${monitor.url}" style="color:#2563eb;text-decoration:none">${monitor.url}</a>
              </td>
            </tr>
            <tr>
              <td style="padding:10px 0;color:#6b7280">Status</td>
              <td style="padding:10px 0;font-weight:700;color:#DC2626">
                ${type}
              </td>
            </tr>
            <tr>
              <td style="padding:10px 0;color:#6b7280">Down Since</td>
              <td style="padding:10px 0;color:#111827">
                ${new Date(startTime).toLocaleString()}
              </td>
            </tr>
            <tr>
              <td style="padding:10px 0;color:#6b7280">Duration</td>
              <td style="padding:10px 0;font-weight:700;color:#DC2626">
                ${downDuration}
              </td>
            </tr>
          </table>

          <div style="margin-top:20px;padding:15px;background:#FEF2F2;border-left:4px solid #DC2626;border-radius:4px">
            <p style="margin:0;color:#7C2D12;font-weight:600;font-size:13px">
              ⚠️ Urgent Action Recommended
            </p>
            <p style="margin:8px 0 0;color:#7C2D12;font-size:13px">
              This service has been experiencing issues for an extended period. Please investigate immediately.
            </p>
          </div>
        </div>

        <!-- Footer -->
        <div style="padding:16px 24px;border-top:1px solid #e5e7eb;background:#fafafa">
          <p style="margin:0;font-size:12px;color:#9ca3af">
            This alert was generated by <strong>PulseWatch Monitoring</strong>.
          </p>
        </div>

      </div>
    </div>
    `;

    await sendEmailAlert({
      to: monitor.alertEmail || user.email,
      subject: `🔴 CRITICAL: ${monitorName} down for ${downDuration}`,
      html,
    });
  } catch (err) {
    console.error("Alert (3min down) error:", err.message);
  }
};
